#mutect_matched:  True
#mutect_tumoronly:  True
#strelka:  True
#varscan:  True
# The number of threads to use for each variant caller that supports parallelization.
#caller_threads:  20
dtexport: "/home/dnousome/Documents/Armstrong"
hgfa: "/home/dnousome/dn/Annotations/ucsc_hg38/GCA_000001405.15_GRCh38_full_analysis_set.fna"
illuminaInt: "/home/dnousome/dn/Annotations/illumina/nextera_hg38_1.bed"
illuminaIntbedgz: "/home/dnousome/dn/Annotations/illumina/illumina_nextera_hg38.bed.gz"
gnomadvcf: "/home/dnousome/dn/Annotations/vcfs/somatic-hg38_af-only-gnomad.hg38.vcf.gz"
smallgnomadvcf: "/home/dnousome/dn/Annotations/vcfs/somatic-hg38_small_exac_common_3.hg38.vcf.gz"
pon: "/home/dnousome/Documents/Aldrin/APOLLO3/WES/2_Variant/pon.vcf.gz"
